name: pst_online
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  google_fonts: any
  dio: any
  dio_http2_adapter: any
  slang: any
  flutter_config: any
  carousel_slider: any
  dots_indicator: any
  flutter_spinkit: any
  font_awesome_flutter: any
  url_launcher: any
  flutter_tawk: any
  permission_handler: any
  path_provider: any
  extended_image: any
  marquee: any
  shimmer: any
  lottie: any
  share_plus: any
  connectivity_plus: any
  device_info_plus: any
  decimal: any
  reactive_forms: any
  reactive_phone_form_field: any
  percent_indicator: any
  package_info_plus: any
  flutter_downloader: any
  get_storage: any
  sliding_up_panel: any
  infinite_scroll_pagination: any
  animate_do: any
  showcaseview: any
  line_icons: any
  dartz: any
  flutter_svg: any
  smooth_page_indicator: any
  internet_connection_checker: any
  intl: any
  slang_flutter: any
  drop_shadow: any
  flutter_staggered_animations: any
  flutter_animated_icons: any
  supabase_flutter: any
  youtube_player_flutter: any
  dynamic_color: any
  sliding_sheet: any
  persistent_bottom_nav_bar: any
  im_stepper: any
  mask_text_input_formatter: any
  fl_chart: any
  upgrader: any
  firebase_core: any
  firebase_analytics: any
  age_calculator: any
  firebase_crashlytics: any
  onesignal_flutter: any
  flutter_cupertino_datetime_picker: any
  flutter_widget_from_html: any
  keyboard_attachable: any
  syncfusion_flutter_pdfviewer: 20.2.49-beta
  flutter_slidable: any
  path_provider_android: any
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  json_serializable: any
  json_annotation: any
  change_app_package_name: any
  flutter_launcher_icons: any
  build_runner: any
  slang_build_runner: any
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/launchers/launcher_icon.png
  android: true
  ios: true
  min_sdk_android: 19

flutter: 
  assets: 
    - assets/logo/
    - assets/animations/
    - assets/icons/
    - assets/images/
  uses-material-design: true

